###
GET http://127.0.0.1:3333/memories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWF0aGV1cyBGb250ZWxlcyIsImF2YXRhclVybCI6Imh0dHBzOi8vYXZhdGFycy5naXRodWJ1c2VyY29udGVudC5jb20vdS85Mjk1NzA4Nj92PTQiLCJzdWIiOiJiMzQ5ZDE5ZC1lYzgzLTQ1MGYtYWNiZC1iM2JjMDgyYWY2YTYiLCJpYXQiOjE2ODQ3MTQ4NjksImV4cCI6MTY4NzMwNjg2OX0.4vBICEVaDREV3kgb3Z_MfPEPRNVKSd-4xC_kQnaZW38


###
POST http://127.0.0.1:3333/memories
Content-Type: application/json

{
  "content": "Teste de memória",
  "coverUrl": "http://127.0.0.1:teste",
  "isPublic": 1
  
}

###
PUT http://127.0.0.1:3333/memories/cad9ed68-8986-4a3c-8240-5eb9a3e08397
Content-Type: application/json

{
  "content": "Update Memory Storage",
  "coverUrl": "http://127.0.0.1:3333"
}

###
DELETE http://127.0.0.1:3333/memories/44d38ee5-ebfb-47d0-8d67-3026306c4eba
Content-Type: application/json


### Auth
POST http://127.0.0.1:3333/register
Content-Type: application/json

{
  "code":"dd3be8ce631e2048d75f"
}
